[customizations.installer.modules]
enable = ["org.fedoraproject.Anaconda.Modules.Localization"]

[customizations.installer.kickstart]
contents = """
lang fr_BE.UTF-8
keyboard --vckeymap=be-latin1 --xlayouts='be'
timezone Europe/Brussels

zerombr
clearpart --all --initlabel
autopart --type=lvm --encrypted --passphrase=placeholder --luks-version=luks2

network --bootproto=dhcp --onboot=yes --activate

user --name=early-setup --password=placeholder --plaintext --groups=wheel

%post --erroronfail --log=/root/anaconda-post.log
bootc switch --mutate-in-place --transport registry <IMAGE_SIGNED> <UPDATE_IMAGE_REF>
%end
"""
